"use client";
import { useState } from "react";
import type { MonthControlModel } from "./month-control-center";
import type { previewMonthControlCenter } from "./actions";
import type { MonthChoiceOperation } from "@/domain/phase2/month-choice-contract";
import { monthChoiceTarget, monthControlCategoryPresets, type MonthControlPurpose } from "@/domain/phase2/month-control-contract";
import { choicePage, rankChoiceCategories } from "@/domain/phase2/month-choice-ui-draft";
import { controlMoney as money } from "@/domain/phase2/month-control-display";
import { useMonthLocalFocus } from "./month-control-focus";
import { LocalChoiceScreen, ChoiceTile, ChoicePages, PercentStepper, primary, secondary } from "./month-choice-controls";
import material from "./month-material.module.css";
import styles from "./month-control-center.module.css";
type Workbench = Awaited<ReturnType<typeof previewMonthControlCenter>>;
type Stage = "CATEGORY" | "OPTION" | "HOW" | "PERCENT" | "AMOUNT" | "RESULT" | "DETAIL" | "MORE" | "ESTIMATE";
export function operationTitle(op: MonthChoiceOperation) {
  return op.kind === "SAVINGS" ? `${money(op.amount, true)} de réservation en moins` : op.strategy === "REDUCE_ONE_OCCURRENCE" ? "Une sortie en moins"
    : op.strategy === "REDUCE_AMOUNT" ? `${money(op.amount)} de moins` : op.percent === "100" ? op.categoryKey === "household-restaurants" ? "Plus aucun restaurant" : "Plus aucune dépense habituelle restante" : op.percent === "50" ? "Deux fois moins" : `−${op.percent} %`;
}
export function MonthControlSimulator({ model, trial, purpose, operations, pending, replaceDraft, recalculate, apply }: {
  model: MonthControlModel; trial: Workbench | null; purpose: MonthControlPurpose; operations: readonly MonthChoiceOperation[]; pending: boolean;
  replaceDraft: (operation: MonthChoiceOperation) => void; recalculate: (ops: readonly MonthChoiceOperation[], purpose: MonthControlPurpose) => void; apply: () => void;
}) {
  const { openEntity } = useMonthLocalFocus();
  const [stage, setStage] = useState<Stage>(operations.length ? "RESULT" : "CATEGORY"), [target, setTarget] = useState(""), [page, setPage] = useState(0), [percent, setPercent] = useState(-20), [amount, setAmount] = useState("25.00"), [precise, setPrecise] = useState(false);
  const category = model.categoryControls.find(row => target === `category:${row.key}`), saving = model.savings.find(row => target === `savings:${row.id}`);
  const categories = rankChoiceCategories(model.categoryControls.filter(row => row.capabilities.adjustability === "ADJUSTABLE" && row.capabilities.strategies.length
    && !operations.some(op => monthChoiceTarget(op) === `category:${row.key}`) && (purpose.kind !== "CATEGORY_CORRECTION" || row.key === purpose.categoryKey)));
  const savings = model.savings.filter(row => row.adjustability === "ADJUSTABLE" && Number(row.amount) > 0 && !operations.some(op => monthChoiceTarget(op) === `savings:${row.id}`) && purpose.kind !== "CATEGORY_CORRECTION");
  const targets = [...categories.map(row => ({ target: `category:${row.key}`, label: row.label, subtitle: `${money(row.reducibleRemaining)} restant ajustable` })), ...savings.map(row => ({ target: `savings:${row.id}`, label: row.label, subtitle: "Réservation ajustable" }))];
  const presets = category ? monthControlCategoryPresets(category.key, category.label, category.capabilities).filter(row => row.operation.strategy !== "REDUCE_ONE_OCCURRENCE" || trial?.shortcuts.some(shortcut => shortcut.categoryKey === category.key && shortcut.operation.strategy === "REDUCE_ONE_OCCURRENCE")) : [];
  const pick = (op: MonthChoiceOperation) => { replaceDraft(op); setStage("RESULT"); };
  const chooseTarget = (next: string) => { setTarget(next); setStage(next.startsWith("savings:") ? "AMOUNT" : "OPTION"); setPrecise(false); setAmount("25.00"); };
  const add = () => { setPage(0); setTarget(""); setStage("CATEGORY"); };
  const reset = () => { recalculate([], model.defaultPurpose); setStage("CATEGORY"); setPage(0); };
  const back = () => stage === "CATEGORY" ? operations.length ? setStage("RESULT") : openEntity("pilot")
    : stage === "OPTION" || saving && stage === "AMOUNT" ? setStage("CATEGORY") : ["DETAIL", "MORE", "ESTIMATE"].includes(stage) ? setStage("RESULT") : stage === "RESULT" ? openEntity(null) : setStage("OPTION");
  const draftAction = () => { if (saving) pick({ kind: "SAVINGS", savingsId: saving.id, strategy: "ADJUST_SAVINGS", amount });
    else if (category && stage === "PERCENT") pick({ kind: "CATEGORY", categoryKey: category.key, strategy: "REDUCE_PERCENT", percent: String(Math.abs(percent)) });
    else if (category) pick({ kind: "CATEGORY", categoryKey: category.key, strategy: "REDUCE_AMOUNT", amount }); };
  const titles: Record<Stage, string> = { CATEGORY: operations.length ? "Ajouter un deuxième choix" : "Que voulez-vous changer ?", OPTION: "Que voulez-vous essayer ?", HOW: "Comment souhaitez-vous réduire ?", PERCENT: "Combien de moins ?", AMOUNT: saving ? "Quelle réservation libérer ?" : "Combien de moins ?", RESULT: "Votre simulation", DETAIL: "Le détail de votre scénario", MORE: "Vos autres budgets cibles", ESTIMATE: "À propos de cette estimation" };
  const footer = stage === "PERCENT" || stage === "AMOUNT" ? <><button type="button" className={styles.textAction} onClick={back}>Précédent</button><button type="button" className={secondary} disabled={pending || stage === "PERCENT" && percent === 0 || stage === "AMOUNT" && !(Number(amount) > 0)} onClick={draftAction}>Voir l’impact</button></>
    : operations.length ? <><button type="button" className={styles.textAction} disabled={pending} onClick={reset}>Réinitialiser</button>{stage === "RESULT" ? <button type="button" className={primary} disabled={pending || !trial?.applicable} onClick={apply}>Appliquer ce scénario</button> : <button type="button" className={secondary} onClick={() => setStage("RESULT")}>Revoir le résultat</button>}</> : undefined;
  return <div className={styles.localChoiceContainer} data-local-focus="simulator"><LocalChoiceScreen kind="simulation" title={titles[stage]} backLabel="Piloter mon mois" subtitle={stage === "RESULT" ? `${operations.length} choix sur 2 · Rien n’est encore enregistré` : category?.label ?? saving?.label ?? "Une simulation, sans modifier le mois enregistré"} back={back} step={["CATEGORY", "OPTION", "RESULT"].includes(stage) ? stage === "CATEGORY" ? 1 : stage === "OPTION" ? 2 : 3 : undefined} total={3} footer={footer}>
    {stage === "CATEGORY" ? <>{purpose.kind !== "FREE_EXPLORATION" && purpose.kind !== "NONE" && <button type="button" className={styles.textAction} onClick={() => recalculate(operations, { kind: "FREE_EXPLORATION" })}>Explorer librement</button>}{!model.projectionSummary.economic ? <p>Les ressources doivent être renseignées pour calculer un scénario.</p> : <><div className={styles.tileGrid}>{choicePage(targets, page).map(row => <ChoiceTile key={row.target} title={row.label} disabled={pending || operations.length >= 2} onClick={() => chooseTarget(row.target)}>{row.subtitle}</ChoiceTile>)}</div><ChoicePages count={targets.length} page={page} setPage={setPage} />{savings.length > 0 && <p className={styles.localSubtitle}>Les cagnottes protégées restent exclues. Une réservation libérée est distincte d’une dépense évitée.</p>}</>}</>
      : stage === "OPTION" ? <div className={styles.optionGrid}>{presets.map(row => <ChoiceTile key={row.label} title={operationTitle(row.operation)} disabled={pending} onClick={() => pick(row.operation)} />)}{category?.capabilities.strategies.some(value => value === "REDUCE_PERCENT" || value === "REDUCE_AMOUNT") && <ChoiceTile title="Personnaliser" onClick={() => setStage("HOW")} />}</div>
      : stage === "HOW" ? <div className={styles.optionGrid}>{category?.capabilities.strategies.includes("REDUCE_PERCENT") && <ChoiceTile title="Réduire d’un pourcentage" onClick={() => setStage("PERCENT")} />}{category?.capabilities.strategies.includes("REDUCE_AMOUNT") && <ChoiceTile title="Réduire d’un montant" onClick={() => setStage("AMOUNT")} />}</div>
      : stage === "PERCENT" ? <div className={styles.centerInteraction}><PercentStepper label="la réduction simulée" valuePercent={percent} onChange={setPercent} min={-100} max={0} shortcuts={[-5, -10, -20]} /><p>Le résultat porte sur ce qui reste ajustable ce mois.</p></div>
      : stage === "AMOUNT" ? precise ? <label className={styles.exactLabel}>Réduire de (€)<input autoFocus className={material.field} type="number" min="0.01" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} /></label> : <><div className={styles.optionGrid}>{[25, 50, 100].map(value => <ChoiceTile key={value} title={money(String(value))} active={Number(amount) === value} onClick={() => setAmount(value.toFixed(2))} />)}<ChoiceTile title="Autre montant" onClick={() => setPrecise(true)} /></div></>
      : stage === "RESULT" ? <>{trial?.preview ? <div className={styles.simulationResult} data-simulation-result=""><div className={styles.selectedChoices}>{operations.map(op => { const row = trial.selected.find(selected => selected.target === monthChoiceTarget(op)); const impact = op.kind === "CATEGORY" ? trial.preview!.categoryImpacts.find(item => item.key === op.categoryKey)?.reduction : trial.reservationRelease;
        return <article key={monthChoiceTarget(op)}><div><strong>{row?.label}</strong><p>{op.kind === "CATEGORY" ? `${money(model.categoryControls.find(category => category.key === op.categoryKey)?.forecast)} → ${money(trial.scenario.categoryControls.find(category => category.key === op.categoryKey)?.forecast)}` : "Dépenses prévues inchangées"} · {operationTitle(op)}</p></div><span>+{money(impact)}{op.kind === "SAVINGS" && <small> réservation libérée</small>}</span><button type="button" className={styles.textAction} onClick={() => { setTarget(monthChoiceTarget(op)); setStage(op.kind === "SAVINGS" ? "AMOUNT" : "OPTION"); setPrecise(false); if (op.kind === "SAVINGS" || op.strategy === "REDUCE_AMOUNT") setAmount(op.amount); else if (op.strategy === "REDUCE_PERCENT") setPercent(-Number(op.percent)); }}>Modifier</button><button type="button" className={styles.textAction} disabled={pending} onClick={() => { recalculate(operations.filter(other => monthChoiceTarget(other) !== monthChoiceTarget(op)), purpose); if (operations.length === 1) setStage("CATEGORY"); }}>Retirer</button></article>; })}</div>
        <div className={styles.impactHero}><strong>+{money(trial.budgetMarginGain)}</strong><p>Marge gagnée</p></div><div className={styles.forecastResult}><span>Fin de mois estimée</span><strong>{money(trial.model.projectionSummary.economic?.central)} → {money(trial.scenario.projectionSummary.economic?.central)}</strong></div>
        <div className={styles.resultLinks}>{operations.length < 2 && <button type="button" className={secondary} onClick={add}>Ajouter un deuxième choix</button>}<button type="button" className={styles.textAction} onClick={() => setStage("DETAIL")}>Voir le détail</button><button type="button" className={styles.textAction} onClick={() => setStage("ESTIMATE")}>ⓘ Estimation</button></div>
      </div> : <div className={styles.emptyChoice}><p>{pending ? "Calcul de votre scénario…" : "Le résultat doit être recalculé."}</p>{!pending && <button type="button" className={secondary} onClick={() => recalculate(operations, purpose)}>Recalculer le scénario</button>}</div>}</>
      : stage === "ESTIMATE" ? <div className={styles.estimationNote}><p>Cette simulation reste indicative.</p><p>Les dépenses déjà réalisées restent comptées.</p><p>Certaines données récentes peuvent encore manquer.</p></div>
      : <div className={styles.simulationDetails}>{(stage === "DETAIL" ? [["Fin de mois", trial?.model.projectionSummary.economic?.central, trial?.scenario.projectionSummary.economic?.central], ["Dépenses variables restantes", trial?.model.projectionSummary.remainingDailyLife, trial?.scenario.projectionSummary.remainingDailyLife], ["Cagnottes protégées", trial?.model.projectionSummary.protectedSavings, trial?.scenario.projectionSummary.protectedSavings]] : [["Écart à l’objectif", trial?.model.projectionSummary.globalDelta, trial?.scenario.projectionSummary.globalDelta], ["Dépassements des budgets cibles", trial?.model.projectionSummary.categoryGap, trial?.scenario.projectionSummary.categoryGap]]).map(([label, before, after]) => <div key={label}><strong>{label}</strong><span>{money(before)} avant</span><span>{money(after)} dans le scénario</span></div>)}{stage === "DETAIL" && <button type="button" className={styles.textAction} onClick={() => setStage("MORE")}>Voir davantage</button>}</div>}
  </LocalChoiceScreen></div>;
}
