"use client";
import { LockKeyhole } from "lucide-react";
import { useState } from "react";
import type { MonthControlModel } from "./month-control-center";
import { useMonthLocalFocus } from "./month-control-focus";
import { ControlFormFields } from "./currency-stepper";
import { updateMonthInputs } from "./actions";
import { controlMoney as money, controlMonth } from "@/domain/phase2/month-control-display";
import { relativeAmountDraft } from "@/domain/phase2/month-choice-ui-draft";
import { LocalChoiceScreen, ChoiceTile, RelativeAmountControl, PercentStepper, TargetGauge, primary, secondary } from "./month-choice-controls";
import material from "./month-material.module.css";
import styles from "./month-control-center.module.css";
type Category = MonthControlModel["categoryControls"][number];
type Saving = MonthControlModel["savings"][number];

export function TargetFocus({ model, category }: { model: MonthControlModel; category: Category }) {
  const { openEntity } = useMonthLocalFocus(), [amount, setAmount] = useState(category.target ?? category.forecast), [clearing, setClearing] = useState(false);
  return <form action={updateMonthInputs} className={styles.choiceForm} data-control-focus={`category:${category.key}`} data-after-save="pilot"><ControlFormFields month={model.targetMonth} intent={clearing ? "clear-category-target" : "save-category-target"} values={{ categoryKey: category.key }} />
    <LocalChoiceScreen title={category.label} backLabel="Retour à Piloter mon mois" subtitle={`Prévision actuelle ≈ ${money(category.forecast)}`} back={() => openEntity("pilot")} footer={<><button type="button" className={styles.textAction} onClick={() => openEntity("pilot")}>Précédent</button><button className={primary}>{clearing ? "Confirmer le retrait" : "Enregistrer le budget cible"}</button></>}>
      {clearing ? <p>Retirer ce budget cible pour ce mois ?</p> : <><RelativeAmountControl reference={category.forecast} initial={amount} name="categoryTarget" label="Votre budget cible" onChange={setAmount} /><div className={styles.targetComparison}><TargetGauge forecast={category.forecast} realized={category.realized} target={amount} /><p>{model.reliability.importsMissing === false ? "Réalisé" : "Réel observé"} {money(category.realized, true)}{model.reliability.importsMissing !== false && " · À consolider"}{category.capabilities.adjustability === "FIXED" && " · Suivi uniquement"}</p></div></>}
      {category.target !== null && <button className={styles.textAction} type="button" onClick={() => setClearing(!clearing)}>{clearing ? "Garder le budget cible" : "Retirer ce budget cible"}</button>}
    </LocalChoiceScreen></form>;
}
export function GoalFocus({ model }: { model: MonthControlModel }) {
  const { openEntity } = useMonthLocalFocus(), [clearing, setClearing] = useState(false);
  const reference = Number(model.projectionSummary.economic?.central) > 0 ? model.projectionSummary.economic!.central : "0.00", [amount, setAmount] = useState(model.settings.goal ?? reference);
  return <form action={updateMonthInputs} className={styles.choiceForm} data-control-focus="global-goal" data-after-save="pilot"><ControlFormFields month={model.targetMonth} intent={clearing ? "clear-month-goal" : "save-month-goal"} />
    <LocalChoiceScreen title="Votre objectif de fin de mois" subtitle={`Fin de mois estimée ${money(model.projectionSummary.economic?.central)}`} back={() => openEntity("pilot")} footer={<><button type="button" className={styles.textAction} onClick={() => openEntity("pilot")}>Précédent</button><button className={primary}>{clearing ? "Confirmer le retrait" : "Enregistrer l’objectif"}</button></>}>
      {clearing ? <p>Retirer l’objectif pour ce mois ?</p> : <><div className={styles.goalWorkbench}><div><span>Projection actuelle</span><strong>{money(reference)}</strong><span>{Number(amount) > Number(reference) ? "Marge nécessaire" : "Objectif atteint"}</span><strong>{money(Math.abs(Number(amount) - Number(reference)).toFixed(2))}</strong></div><label className={styles.exactLabel}>Objectif (€)<input autoFocus className={material.field} name="monthGoal" type="number" min="0" step="0.01" required value={amount} onChange={event => setAmount(event.target.value)} /><span className={styles.quickChoices}>{[5,10,20].map(percent => <button type="button" key={percent} className={styles.smallChoice} onClick={() => setAmount(relativeAmountDraft(reference,percent))}>+{percent} %</button>)}</span></label></div></>}
      {model.settings.goal !== null && <button className={styles.textAction} type="button" onClick={() => setClearing(!clearing)}>{clearing ? "Garder l’objectif" : "Retirer l’objectif"}</button>}
    </LocalChoiceScreen></form>;
}
export function AdjustmentFocus({ model, category }: { model: MonthControlModel; category: Category }) {
  const { openEntity } = useMonthLocalFocus();
  const setting = model.settings.assumptions[category.key], reference = model.habitualControls.find(row => row.key === category.key)?.reducibleRemaining ?? category.reducibleRemaining;
  const [step, setStep] = useState<"MODE" | "LOWER" | "HIGHER" | "CUSTOM" | "NONE">("MODE"), [percent, setPercent] = useState(setting?.mode === "HIGHER" ? 20 : -20), [amount, setAmount] = useState(setting?.amount ?? reference);
  const draft = step === "LOWER" || step === "HIGHER" ? relativeAmountDraft(reference, percent) : amount;
  // Fixed ±20 % modes retain their meaning. Other draft percentages use the
  // existing absolute CUSTOM remainder, never a persisted percentage rule.
  const mode = step === "NONE" ? "NONE" : step === "LOWER" && percent === -20 ? "LOWER" : step === "HIGHER" && percent === 20 ? "HIGHER" : "CUSTOM";
  return <form action={updateMonthInputs} className={styles.choiceForm} data-control-focus={`choice:${category.key}`} data-after-save={`pilot:category:${category.key}`}><ControlFormFields month={model.targetMonth} intent={mode === "NONE" ? "clear-month-assumption" : "save-month-assumption"} values={{ categoryKey: category.key, assumptionMode: mode, assumptionAmount: draft }} />
    <LocalChoiceScreen kind="persisted" title={`${category.label} pour ${controlMonth(model.targetMonth)}`} subtitle={step === "MODE" ? "Par rapport à vos habitudes :" : step === "LOWER" ? "Combien moins ?" : step === "HIGHER" ? "Combien plus ?" : undefined} back={() => step === "MODE" ? openEntity(`pilot:category:${category.key}`) : setStep("MODE")} step={step === "MODE" ? 1 : 2} total={2} footer={step !== "MODE" ? <><button type="button" className={styles.textAction} onClick={() => setStep("MODE")}>Précédent</button><button className={primary}>Enregistrer l’ajustement</button></> : undefined}>
      {step === "MODE" ? <div className={styles.optionGrid}>{(["LOWER", "NONE", "HIGHER", "CUSTOM"] as const).map((key, index) => <ChoiceTile key={key} title={["Moins", "Comme d’habitude", "Plus", "Montant précis"][index]!} onClick={() => { setStep(key); if (key === "LOWER") setPercent(-20); if (key === "HIGHER") setPercent(20); }} />)}</div> : step === "NONE" ? <div className={styles.emptyChoice}><h3>Revenir à vos habitudes</h3><p>L’ajustement de ce mois sera retiré.</p></div> : step === "CUSTOM" ? <label className={styles.exactLabel}>Reste habituel prévu (€)<input autoFocus className={material.field} value={amount} type="number" min="0" step="0.01" required onChange={event => setAmount(event.target.value)} /></label> : <div className={styles.centerInteraction}><PercentStepper valuePercent={percent} onChange={setPercent} label="l’ajustement" min={step === "LOWER" ? -100 : 0} max={step === "LOWER" ? 0 : 500} shortcuts={step === "LOWER" ? [-10, -20, -30] : [10, 20, 30]} /><div className={styles.draftAmount}><span>Reste habituel choisi</span><strong>{money(draft)}</strong></div><p className={styles.localSubtitle}>Le réalisé et les projets explicites restent comptés.</p></div>}
    </LocalChoiceScreen></form>;
}
export function SavingsFocus({ model, saving }: { model: MonthControlModel; saving?: Saving }) {
  const { openEntity } = useMonthLocalFocus(), [step, setStep] = useState(saving ? 2 : 1), [precise, setPrecise] = useState(false), [options, setOptions] = useState(false), [remove, setRemove] = useState(false);
  const [label, setLabel] = useState(saving?.label ?? ""), [amount, setAmount] = useState(saving?.amount ?? "0.00"), [protection, setProtection] = useState(saving?.adjustability ?? "PROTECTED"), [date, setDate] = useState(saving?.dueDate ?? "");
  const titles = ["Pour quel projet ?", saving ? "Ajuster cette cagnotte" : "Combien mettre de côté ?", "Protéger cette cagnotte ?", "Une date particulière ?", "Votre cagnotte"];
  const valid = step === 1 ? label.trim().length > 0 : step === 2 ? Number(amount) > 0 : true;
  if (saving?.adjustability === "PROTECTED") return <LocalChoiceScreen title={saving.label} backLabel="Mes cagnottes" back={() => openEntity("savings")}><div className={styles.savingConfirmation}><LockKeyhole size={32} aria-label="Protégée" /><strong>{money(saving.amount, true)}</strong><h3>Intouchable ce mois-ci</h3><p>Cette épargne n’est ni modifiable ni proposée dans une simulation.</p></div></LocalChoiceScreen>;
  return <form action={updateMonthInputs} className={styles.choiceForm} data-save-ready={step === 5 || remove} data-control-focus={saving ? `savings:${saving.id}` : "savings:new"} data-after-save="savings"><ControlFormFields month={model.targetMonth} intent={remove ? "remove-declared-outflow" : saving ? "update-declared-savings" : "add-declared-savings"} values={{ ...(saving ? { outflowId: saving.id } : {}), outflowLabel: label, outflowAmount: amount, outflowAdjustability: protection, outflowDate: date }} />
    <LocalChoiceScreen title={remove ? "Supprimer cette cagnotte ?" : titles[step - 1]!} subtitle={saving ? `${saving.label} · ${money(saving.amount, true)} actuellement` : undefined} back={() => remove ? setRemove(false) : step > (saving ? 2 : 1) ? setStep(step - 1) : openEntity("savings")} step={step} total={5} footer={<><button type="button" className={styles.textAction} onClick={() => remove ? setRemove(false) : step > 1 ? setStep(step - 1) : openEntity("savings")}>Précédent</button>{remove ? <button className={styles.dangerAction}>Confirmer la suppression</button> : step === 5 ? <button key="confirm-saving" type="submit" className={primary}>{saving ? "Enregistrer la cagnotte" : "Créer la cagnotte"}</button> : <button type="button" key="continue-saving" className={secondary} disabled={!valid} onClick={event => { event.preventDefault(); setStep(step + 1); }}>Continuer</button>}</>}>
      {remove ? <p>La réservation de {money(amount, true)} sera retirée de ce mois.</p> : step === 1 ? <label className={styles.exactLabel}>Pour quoi mettez-vous de l’argent de côté ?<input className={material.field} autoFocus value={label} maxLength={120} onChange={event => setLabel(event.target.value)} placeholder="Voyage, Noël…" /></label> : step === 2 ? saving && Number(saving.amount) > 0 ? <RelativeAmountControl reference={saving.amount} initial={amount} name="savingDraftAmount" label="Nouveau montant" onChange={setAmount} /> : precise ? <label className={styles.exactLabel}>Montant (€)<input autoFocus className={material.field} type="number" min="0.01" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} /></label> : <><div className={styles.optionGrid}>{[100, 250, 500, 1000].map(value => <ChoiceTile key={value} title={money(String(value))} active={Number(amount) === value} onClick={() => setAmount(value.toFixed(2))} />)}</div><button type="button" className={styles.textAction} onClick={() => setPrecise(true)}>Autre montant</button></> : step === 3 ? <div className={styles.optionGrid}><ChoiceTile title="La protéger" active={protection === "PROTECTED"} onClick={() => setProtection("PROTECTED")}>Elle ne sera jamais proposée comme source d’ajustement.</ChoiceTile><ChoiceTile title="La laisser ajustable" active={protection === "ADJUSTABLE"} onClick={() => setProtection("ADJUSTABLE")}>Elle pourra apparaître dans certaines simulations.</ChoiceTile></div> : step === 4 ? <div className={styles.centerInteraction}><div className={styles.optionGrid}><ChoiceTile title="Pas de date" active={!date} onClick={() => setDate("")} /><ChoiceTile title="Choisir une date" active={!!date} onClick={() => setDate(date || model.asOf)} /></div>{date && <label className={styles.exactLabel}>Date de mise de côté<input className={material.field} type="date" value={date} onChange={event => setDate(event.target.value)} /></label>}</div> : <div className={styles.savingConfirmation}><h3>{label}</h3><strong>{money(amount, true)}</strong><p>{protection === "PROTECTED" ? "Protégée" : "Ajustable"}</p><p>{date ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "long", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)) : "Sans date"}</p>{saving && <button type="button" className={styles.textAction} onClick={() => setStep(1)}>Modifier le nom</button>}</div>}
      {saving && step === 2 && !remove && <div className={styles.savingOptions}><button type="button" className={styles.textAction} onClick={() => setOptions(!options)}>Plus d’options</button>{options && <button type="button" className={styles.dangerAction} onClick={() => setRemove(true)}>Supprimer cette cagnotte</button>}</div>}
    </LocalChoiceScreen></form>;
}
