import type { projectPastMonthReview } from "@/server/phase2/past-month-review";
const money = (value: string | null) => value === null ? "Non disponible" : new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(Number(value));
export function PastMonthView({ targetMonth, review }: { targetMonth: string; review: ReturnType<typeof projectPastMonthReview> }) {
  const month = new Intl.DateTimeFormat("fr-FR", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${targetMonth}-01T12:00:00Z`));
  const adjacent = (delta: number) => { const date = new Date(`${targetMonth}-01T12:00:00Z`); date.setUTCMonth(date.getUTCMonth() + delta); return date.toISOString().slice(0, 7); };
  return <main className="mx-auto max-w-5xl space-y-6 pb-20 text-slate-900"><nav aria-label="Mois consulté" className="flex justify-between text-sm font-bold"><a className="underline" href={`/mois-a-venir?month=${adjacent(-1)}`}>Mois précédent</a><a className="underline" href={`/mois-a-venir?month=${adjacent(1)}`}>Mois suivant</a><a className="underline" href="/mois-a-venir">Mois à venir</a></nav>
    <header><p className="eyebrow">Notre bilan du mois passé</p><h1 className="mt-2 text-4xl font-black capitalize">{month}</h1><p className="mt-2 text-slate-600">Prévu, réalisé et écart, à partir des prévisions réellement conservées et des opérations importées.</p></header>
    {!review.complete && <p role="status" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Couverture des imports incomplète : les montants observés sont partiels. Aucun écart définitif ni erreur de calibration ne peut être validé.</p>}
    <section className="card p-6"><h2 className="text-xl font-black">Nos estimations au fil du mois</h2><div className="mt-4 grid grid-cols-3 gap-4">{review.checkpoints.map(({ horizon, row }) => <div key={horizon}><h3 className="text-sm font-bold">{horizon === "START" ? "Début" : horizon === "MID" ? "Milieu" : "Fin"} du mois</h3><p className="mt-2 text-lg font-black">{row ? money(row.payload.final.central) : "Non conservée"}</p>{row && <p className="mt-1 text-xs text-slate-500">Estimation au {row.as_of_date} · repère économique</p>}</div>)}</div><p className="mt-4 text-xs text-slate-500">Une prévision absente n’est pas reconstruite après coup. Le résultat bancaire réel se consulte dans l’historique.</p></section>
    <section className="card p-6"><h2 className="text-xl font-black">Prévu / réalisé / écart par catégorie</h2><table className="mt-4 w-full text-sm"><caption className="mb-3 text-left text-xs text-slate-500">Prévu au début du mois, puis coûts canoniques {review.complete ? "réalisés" : "observés partiellement"}. Un écart positif signifie un coût supérieur à la prévision.</caption><thead><tr className="border-b text-left"><th scope="col" className="pb-3">Catégorie</th><th scope="col">Prévu</th><th scope="col">{review.complete ? "Réalisé" : "Observé partiel"}</th><th scope="col">Écart</th></tr></thead><tbody>{review.categories.map(c => <tr key={c.key} className="border-b border-slate-100"><th scope="row" className="py-3 text-left font-semibold">{c.label}</th><td>{c.expected === null ? "Non conservé" : money(c.expected)}</td><td>{money(c.observed)}</td><td>{c.difference === null ? "À affiner" : money(c.difference)}</td></tr>)}</tbody></table><p className="mt-4 text-xs text-slate-600">Total {review.complete ? "réalisé" : "observé"} de ces catégories : {money(review.actualSelectedCategories)}. Ce total n’est pas le reste économique de tout le foyer.</p><a className="mt-4 inline-block font-bold text-emerald-900 underline" href={`/historique/${targetMonth}`}>Voir le bilan historique complet</a></section>
  </main>;
}
