import type { previewPlannedExpense } from "./planned-expenses-actions";
type Preview = Extract<Awaited<ReturnType<typeof previewPlannedExpense>>, { ok: true }>["value"];
const money = (value: string) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(Number(value));
export function PlannedImpactCard({ preview, fundingIncomplete }: { preview: Preview; fundingIncomplete: boolean }) {
  return <article className="grid grid-cols-2 gap-5" aria-label="Effet sur notre mois">
    <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h4 className="text-xs font-bold tracking-wider text-slate-500">VOTRE PROJET</h4>
      <dl className="mt-4 grid gap-3">{preview.economicLines.map((line) => <div className="flex justify-between gap-3 text-sm" key={line.id}><dt>{line.label}{line.economicOnly && <span className="block text-xs text-slate-500">Usage économique estimé</span>}</dt><dd className="whitespace-nowrap font-semibold">{money(line.amount)}</dd></div>)}</dl>
      <div className="mt-4 flex justify-between border-t border-slate-200 pt-4 font-bold"><span>Coût prévu</span><span>{money(preview.grossCost)}</span></div>
      {Number(preview.fuelUsage) > 0 && <p className="mt-3 text-xs leading-5 text-slate-500">Le carburant représente l’usage estimé du trajet. Ce n’est pas un paiement bancaire programmé.</p>}
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="text-xs font-bold tracking-wider text-slate-500">PAIEMENT PRÉVU</h4>
      {fundingIncomplete ? <p className="mt-4 text-sm text-amber-800">Le financement reste à compléter. L’effet économique du projet est calculable.</p> : <dl className="mt-4 grid gap-3">{([ ["Banque", preview.projectPayment.bank], ["Swile", preview.projectPayment.swile], ["Edenred", preview.projectPayment.edenred] ] as const).filter(([, amount]) => Number(amount) > 0).map(([label, amount]) => <div className="flex justify-between text-sm" key={label}><dt>{label}</dt><dd className="font-semibold">{money(amount)}</dd></div>)}{Number(preview.payableGross) === 0 && <p className="text-sm text-slate-500">Aucun paiement prévu.</p>}</dl>}
      {([ ["Swile", preview.funding.swile], ["Edenred", preview.funding.edenred] ] as const).filter(([, pocket]) => Number(pocket.shortfall) > 0).map(([label, pocket]) => <p className="mt-3 text-sm text-amber-800" key={label}>{label} : {money(pocket.shortfall)} à financer autrement avant l’enregistrement.</p>)}
      {(Number(preview.projectPayment.swile) > 0 || Number(preview.projectPayment.edenred) > 0) && <p className="mt-4 text-xs text-slate-500">Les titres-restaurants choisis sont réservés dans la projection du mois.</p>}
    </section>
    <section className="col-span-2 rounded-2xl bg-indigo-50 p-5"><h4 className="text-xs font-bold tracking-wider text-indigo-800">EFFET SUR LE MOIS</h4><p className="mt-3 max-w-3xl text-base leading-7 text-indigo-950">{preview.effectNarrative}</p></section>
    <section className="rounded-2xl border border-slate-200 p-5"><h4 className="text-xs font-bold tracking-wider text-slate-500">PROJECTION HABITUELLE</h4><dl className="mt-4 grid gap-3">{([ ["Avant ce projet", preview.before.central], ["Avec ce projet", preview.after.central], ["Écart", preview.remainingDifference] ] as const).map(([label, value]) => <div className="flex justify-between gap-3 text-sm" key={label}><dt>{label}</dt><dd className="font-bold">{preview.projectionIncomplete && label !== "Écart" ? "À affiner" : <>{label === "Écart" && Number(value) > 0 ? "+" : ""}{money(value)}</>}</dd></div>)}</dl></section>
    <section className="rounded-2xl bg-indigo-950 p-5 text-white"><h4 className="text-xs font-bold tracking-wider text-indigo-200">PROJECTION DE FIN DE MOIS</h4><dl className="mt-4 grid gap-3">{([ ["Mois plus léger", preview.after.lowConsumption], ["Habituel", preview.after.central], ["Mois plus coûteux", preview.after.highConsumption] ] as const).map(([label, value]) => <div className="flex justify-between text-sm" key={label}><dt>{label}</dt><dd className="font-bold">{preview.projectionIncomplete ? "À affiner" : money(value)}</dd></div>)}</dl><p className="mt-4 text-xs text-indigo-200">{preview.projectionIncomplete ? "Les imports du mois sont incomplets. L’effet estimé de ce projet reste visible ; la projection complète est à affiner." : "Reste projeté du mois, titres-restaurants inclus."}</p></section>
    <details className="col-span-2 text-xs text-slate-500"><summary className="cursor-pointer font-semibold">Comprendre la projection</summary><p className="mt-2 leading-5">{preview.explanation} Ces estimations mensuelles ne représentent pas un solde bancaire futur.</p></details>
  </article>;
}
