"use client";
import { useState, type Dispatch, type SetStateAction } from "react";
import { ArrowLeft, ChevronRight, MapPin } from "lucide-react";
import { PLANNED_SUBTYPE_LABELS, rootAssetModule, plannedAsset, type AssetModule, type PlannedExpenseFamily } from "@/domain/phase2/planned-assets";
import { acceptBuilderChild, availableBuilderChildren, changeBuilderContext, commitBuilderCost, discardSuspended, editBuilderDraft,
  fundBuilderTotal, itemizeBuilderCosts, materializeBuilderDraft, removeBuilderCost, setBuilderRootBaseline, setQuickTotal,
  suggestedBuilderChildren, undoBuilderChange, deriveBuilderReadiness, canCollapseBuilderCosts, collapseBuilderCosts, type BuilderIssue, type BuilderState } from "@/domain/phase2/planned-builder";
import { BUILDER_INTENTS, PARTY_CHOICES, PURCHASE_CHOICES, compatibleWallets, detailActionLabel, draftSummary,
  intentForDraft, projectPlaceLabel, uxAssetGroup, visibleUxAssets } from "@/domain/phase2/planned-ux";
import { builderAssetChoices, isRootCost } from "@/domain/phase2/planned-product";
import { DELIVERY_PROVIDERS, SOCIAL_CONTACTS_V1, plannedContextModifiers, resolvePlannedContext } from "@/domain/phase2/planned-rules";
import { rankPlacesForPlannedContext, habitualPlaceSuggestions, type PlannedPlaceOption } from "@/domain/phase2/planned-places";
import type { CostItem, PlannedExpenseContext, PlannedPriceSuggestion, PlannedVehicleEstimate, PlannedWalletOption, ProspectivePersonRef } from "@/domain/phase2/planned-contract";
import { IntentTile, ChoiceTiles, OptionalAction, LocalAssetEditor, ContextualBlockerCTA, builderButton, builderInput, builderPrimary, builderMoney } from "./planned-builder-primitives";
import { PlannedRouteEditor } from "./planned-route-editor";
import { PlannedParticipants } from "./planned-people-fields";
import { isAssumedOnsiteWorkday } from "@/domain/phase2/workday-assumption";

const contactLabel = (ref?: ProspectivePersonRef) => ref?.kind === "CONTACT" ? SOCIAL_CONTACTS_V1.find((part) => part.key === ref.contactKey)?.label : ref?.kind === "TEXT" ? ref.label : undefined;
function ContactPicker({ label, value, onChange }: { label: string; value?: ProspectivePersonRef; onChange: (ref: ProspectivePersonRef) => void }) {
  return <div className="grid gap-3"><ChoiceTiles label={label} value={value?.kind === "CONTACT" ? value.contactKey : value?.kind} choices={[
    ...SOCIAL_CONTACTS_V1.map((contact) => ({ key: contact.key, label: contact.label })), { key: "TEXT", label: "Quelqu’un d’autre" }]} onChange={(key) => onChange(key === "TEXT" ? { kind: "TEXT", label: "" } : { kind: "CONTACT", contactKey: key })} />
    {value?.kind === "TEXT" && <label className="grid max-w-md gap-1 text-sm">Son nom<input className={builderInput} value={value.label} onChange={(event) => onChange({ kind: "TEXT", label: event.target.value })} /></label>}</div>;
}
function PlacePicker({ places, value, onChange, brandFirst = false, seller, onSeller, exact = false }: {
  places: readonly PlannedPlaceOption[]; value: PlannedExpenseContext["place"]; onChange: (ref?: PlannedExpenseContext["place"]) => void;
  brandFirst?: boolean; seller?: string; onSeller?: (label?: string) => void; exact?: boolean;
}) {
  const [manual, setManual] = useState(value?.kind === "TEXT"), [all, setAll] = useState(false), [precise, setPrecise] = useState(exact || !!value);
  const suggestions = habitualPlaceSuggestions(places);
  const known = value?.kind === "KNOWN" ? places.find((part) => part.placeId === value.placeId) : undefined;
  const brands = [...new Set(suggestions.map((part) => part.brandLabel || part.name))];
  const candidates = (all ? places : suggestions).filter((place) => !brandFirst || !seller || (place.brandLabel || place.name) === seller);
  return <div className="grid gap-3">{brandFirst && <><ChoiceTiles label="Quelle enseigne ?" choices={brands.map((label) => ({ key: label, label }))} value={seller} onChange={(label) => { onSeller?.(label); onChange(undefined); }} />
      <label className="grid max-w-md gap-1 text-sm">Autre enseigne<input className={builderInput} value={seller ?? ""} onChange={(event) => { onSeller?.(event.target.value || undefined); onChange(undefined); }} /></label></>}
    {brandFirst && !precise && !exact ? <button className="text-left text-sm font-semibold text-indigo-700" onClick={() => setPrecise(true)}>+ Préciser l’établissement</button> : <>
      {known && <p className="text-sm font-semibold">{known.name} · {known.commune}<button className="ml-3 text-indigo-700 underline" onClick={() => { onChange(undefined); setAll(true); }}>Changer</button></p>}
      <label className="grid max-w-xl gap-1 text-sm">{brandFirst ? "Établissement" : "Lieu"}<select className={builderInput} value={value?.kind === "KNOWN" ? value.placeId : manual ? "TEXT" : ""} onChange={(event) => { setManual(event.target.value === "TEXT"); onChange(event.target.value === "TEXT" ? { kind: "TEXT", label: "", provenance: "USER_DECLARED_PROSPECTIVE" } : event.target.value ? { kind: "KNOWN", placeId: event.target.value } : undefined); }}>
        <option value="">Sans lieu précisé</option>{[...candidates, ...known && !candidates.includes(known) ? [known] : []].map((place, index) => <option key={place.placeId} value={place.placeId}>{place.name}{place.commune ? ` · ${place.commune}` : ""}{!all && index === 0 && suggestions.length ? " · Habituel" : ""}</option>)}<option value="TEXT">Autre lieu à saisir</option></select></label>
      {!all && <button type="button" className="text-left text-xs text-indigo-700 underline" onClick={() => setAll(true)}>Voir tous les lieux compatibles, y compris les lieux rares</button>}
      {value?.kind === "TEXT" && <label className="grid max-w-xl gap-1 text-sm">Nom du lieu ou destination<input className={builderInput} value={value.label} onChange={(event) => onChange({ kind: "TEXT", label: event.target.value, provenance: "USER_DECLARED_PROSPECTIVE" })} /></label>}
      {!candidates.length && <p className="text-xs text-slate-500">Aucun lieu habituel compatible observé. Vous pouvez choisir un lieu rare ou saisir votre destination.</p>}
    </>}</div>;
}

function TripAccommodation({ items, onConfirm, onRemove }: { items: readonly CostItem[]; onConfirm: (item: CostItem) => void; onRemove: (id: string) => void }) {
  const [kind, setKind] = useState("");
  const existing = items.filter((item) => item.assetKey === "trip:hotel" || item.assetKey === "trip:airbnb");
  const asset = plannedAsset(kind === "HOTEL" ? "trip:hotel" : "trip:airbnb");
  return <OptionalAction label="Ajouter un hébergement" active={existing.length > 0}><ChoiceTiles label="Où serez-vous hébergés ?" value={kind} onChange={setKind} choices={[
    { key: "HOTEL", label: "Hôtel" }, { key: "RENTAL", label: "Airbnb / location" }, { key: "RELATIVE", label: "Chez un proche" }, { key: "OTHER", label: "Autre" }]} />
    {kind === "RELATIVE" && <p className="mt-3 text-sm text-slate-600">Aucun coût d’hébergement ajouté.{existing.length > 0 && " Un hébergement reste chiffré ci-dessous : retirez-le si vous êtes finalement hébergés gratuitement."}</p>}
    {(kind === "HOTEL" || kind === "RENTAL") && !existing.some((item) => item.assetKey === asset?.assetKey) && <div className="mt-3 max-w-sm"><LocalAssetEditor key={kind} asset={asset} wallets={[]} initiallyEditing onConfirm={onConfirm} /></div>}
    {kind === "OTHER" && <div className="mt-3 max-w-sm"><LocalAssetEditor wallets={[]} onConfirm={onConfirm} /></div>}
    {existing.map((item) => <div className="mt-3 max-w-sm" key={`${item.id}:${item.unitAmount}`}><LocalAssetEditor asset={plannedAsset(item.assetKey!)} item={item} wallets={[]} onConfirm={onConfirm} onRemove={() => onRemove(item.id)} /></div>)}
  </OptionalAction>;
}

type Props = { builder: BuilderState; setBuilder: Dispatch<SetStateAction<BuilderState>>; step: number; setStep: (step: number) => void;
  selectRoot: (family: PlannedExpenseFamily, subtype: string | null) => void; persons: readonly { personId: string; displayName: string }[];
  places: readonly PlannedPlaceOption[]; wallets: readonly PlannedWalletOption[]; prices: readonly PlannedPriceSuggestion[];
  vehicle: PlannedVehicleEstimate | null; targetMonth: string; busy: boolean; onPreview: () => void };

export function PlannedIntentBuilder({ builder, setBuilder, step, setStep, selectRoot, persons, places, wallets, prices, vehicle, targetMonth, busy, onPreview }: Props) {
  const [undoNotice, setUndoNotice] = useState("");
  const [bring, setBring] = useState(false), [pathChild, setPathChild] = useState<AssetModule | null>(null);
  const [walletSource, setWalletSource] = useState<"SWILE" | "EDENRED">("SWILE"), [walletAmount, setWalletAmount] = useState(""), [mealAmount, setMealAmount] = useState("");
  const [fundingError, setFundingError] = useState("");
  const draft = builder.draft, context = draft.context, root = rootAssetModule(draft.familyKey, draft.subtypeKey);
  const intent = intentForDraft(draft), isVisit = intent === "visit", isWork = intent === "work_meal", isDelivery = context.purchaseMode === "DELIVERY" || context.workMealMode === "DELIVERED";
  const personName = persons.find((person) => person.personId === context.participantPersonIds?.[0])?.displayName;
  const resolved = draft.subtypeKey || draft.familyKey === "other" ? resolvePlannedContext({ familyKey: draft.familyKey, subtypeKey: draft.subtypeKey, modifiers: plannedContextModifiers(context, personName) }) : null;
  const related = context.host ?? context.personVisited;
  const compatible = resolved ? rankPlacesForPlannedContext(places, resolved, { contactKey: related?.kind === "CONTACT" ? related.contactKey : undefined,
    workMealPersonName: isWork ? personName : undefined, assetKeys: draft.costItems.flatMap((item) => item.assetKey ? [item.assetKey] : []),
    giftAssetKey: draft.costItems.find((item) => item.assetKey?.startsWith("gift:"))?.assetKey ?? undefined }).map((part) => part.place) : [];
  const readiness = deriveBuilderReadiness(builder, { places, workMealPersonName: isWork ? personName : undefined });
  const activeDraft = materializeBuilderDraft(builder), summary = draftSummary(activeDraft.costItems);
  const eligibleWallets = compatibleWallets(wallets, context, isWork);
  const selectedWallet = eligibleWallets.find((part) => part.source === walletSource)?.source ?? eligibleWallets[0]?.source ?? walletSource;
  const path = pathChild && builder.acceptedChildren.includes(pathChild) ? [root, pathChild] as const : [root] as const;
  const module = path.at(-1)!;
  const catalog = resolved ? visibleUxAssets(builderAssetChoices(resolved, module, context, bring ? "BRING_ITEMS" : "MODULE"), context) : [];
  const groups = [...new Set(catalog.map(uxAssetGroup))];
  const placeLabel = projectPlaceLabel(context, places);
  const changeContext = (change: Partial<PlannedExpenseContext>) => {
    setBuilder((state) => changeBuilderContext(state, { ...state.draft.context, ...change }));
    // Ordinary choices do not leave a permanent Undo banner. Incompatible explicit
    // values show their contextual repair/Undo through builder.suspended below.
    setUndoNotice("");
  };
  const repair = (issue: BuilderIssue) => {
    const target = document.getElementById(issue.repairTarget) ?? document.getElementById(issue.repairTarget.startsWith("funding-") ? "builder-cost" : "builder-context");
    target?.scrollIntoView({ behavior: "smooth", block: "center" }); target?.querySelector<HTMLElement>("input, select, button")?.focus();
  };
  const date = <label className="grid max-w-xs gap-1 text-sm font-semibold">{intent === "purchase" ? "Quand pensez-vous l’acheter ?" : intent === "trip" ? "Départ" : "Quand ?"}<span className="text-xs font-normal text-slate-500">Facultatif</span><input className={builderInput} type="date" min={`${targetMonth}-01`} max={new Date(Date.UTC(Number(targetMonth.slice(0, 4)), Number(targetMonth.slice(5, 7)), 0)).toISOString().slice(0, 10)} value={draft.plannedDate ?? ""} onChange={(event) => setBuilder((state) => editBuilderDraft(state, { ...state.draft, plannedDate: event.target.value || null }))} /></label>;
  const companions = <><ChoiceTiles label={intent === "fast_food" ? "Pour qui ?" : "Avec qui ?"} choices={[{ key: "SOLO", label: "Seul" }, { key: "COUPLE", label: "À deux" }, { key: "GROUP", label: "À plusieurs" }]} value={context.companionMode} onChange={(mode) => changeContext({ companionMode: mode as PlannedExpenseContext["companionMode"], participantPersonIds: mode === "SOLO" ? persons.slice(0, 1).map((person) => person.personId) : persons.map((person) => person.personId), additionalGuestCount: mode === "GROUP" ? 2 : undefined })} />
    {context.companionMode === "GROUP" && <label className="grid max-w-xs gap-1 text-sm">Combien serez-vous ?<input type="number" min={2} max={99} className={builderInput} value={(context.participantPersonIds?.length ?? 0) + (context.additionalGuestCount ?? 0)} onChange={(event) => changeContext({ additionalGuestCount: Math.max(0, Number(event.target.value) - (context.participantPersonIds?.length ?? 0)) })} /></label>}</>;
  const occasion = <OptionalAction label="Occasion spéciale" active={!!context.socialOccasion && context.socialOccasion !== "NONE"}><ChoiceTiles label="Quelle occasion ?" value={context.occasionLabel === "Saint-Valentin" ? "VALENTINE" : context.socialOccasion} choices={[{ key: "NONE", label: "Sans occasion particulière" }, { key: "VALENTINE", label: "Saint-Valentin" }, { key: "BIRTHDAY", label: "Anniversaire" }, { key: "CHRISTMAS", label: "Noël" }, { key: "CELEBRATION", label: "Célébration" }, { key: "OTHER_SPECIAL", label: "Autre" }]} onChange={(key) => changeContext({ socialOccasion: key === "VALENTINE" ? "OTHER_SPECIAL" : key as PlannedExpenseContext["socialOccasion"], occasionLabel: key === "VALENTINE" ? "Saint-Valentin" : undefined })} />{context.socialOccasion === "OTHER_SPECIAL" && context.occasionLabel !== "Saint-Valentin" && <input className={`${builderInput} mt-3`} aria-label="Occasion" value={context.occasionLabel ?? ""} onChange={(event) => changeContext({ occasionLabel: event.target.value || undefined })} />}</OptionalAction>;
  const place = resolved && resolved.fields.place !== "HIDDEN" && resolved.place.source !== "OWN_HOME" ? <OptionalAction label={isWork ? "Préciser le commerce" : intent === "restaurant" || intent === "fast_food" ? "Préciser le restaurant" : intent === "groceries" ? "Préciser le magasin" : intent === "purchase" ? "Préciser le magasin" : "Préciser le lieu"} active={!!context.place && resolved.place.source !== "CONTACT_HOME"}>
    <PlacePicker places={compatible} value={context.place} onChange={(place) => changeContext({ place })} brandFirst={intent === "groceries" || intent === "purchase"} seller={context.seller} onSeller={(seller) => changeContext({ seller })} exact={context.transportMode === "CAR"} /></OptionalAction> : null;
  const provider = <div className="grid gap-3"><ChoiceTiles label="Comment sera-t-il livré ?" value={context.deliveryProviderKey} choices={DELIVERY_PROVIDERS.filter((part) => ["UBER_EATS", "DELIVEROO", "DIRECT", "OTHER"].includes(part.key)).map((part) => ({ key: part.key, label: part.label }))} onChange={(key) => { const provider = DELIVERY_PROVIDERS.find((part) => part.key === key)!; changeContext({ deliveryProviderKey: key, deliveryProvider: provider.label }); }} />
    {context.deliveryProviderKey === "OTHER" && <label className="grid max-w-md gap-1 text-sm">Qui livre ?<input className={builderInput} value={context.deliveryProvider === "Autre" ? "" : context.deliveryProvider ?? ""} onChange={(event) => changeContext({ deliveryProvider: event.target.value || undefined })} /></label>}
    <OptionalAction label={intent === "groceries" ? "Préciser l’enseigne" : "Préciser le commerce"} active={!!context.seller}><label className="grid max-w-md gap-1 text-sm">{intent === "groceries" ? "Quelle enseigne ?" : "Quel commerce prépare la commande ?"}<input className={builderInput} value={context.seller ?? ""} onChange={(event) => changeContext({ seller: event.target.value || undefined })} placeholder={intent === "groceries" ? "Ex. Carrefour" : "Ex. Domino’s"} /></label></OptionalAction></div>;
  const participants = <OptionalAction label={isVisit ? "Préciser qui y va" : "Préciser qui vient"}><PlannedParticipants context={context} persons={persons} onChange={(context) => changeContext(context)} /></OptionalAction>;
  const channel = <OptionalAction label={intent === "purchase" ? "Préciser où acheter" : "Préciser comment"} active={!!context.purchaseMode}><ChoiceTiles label={intent === "purchase" ? "Comment pensez-vous l’acheter ?" : "Comment ferez-vous les courses ?"} value={context.purchaseMode} choices={intent === "purchase" ? [{ key: "IN_STORE", label: "En magasin" }, { key: "ONLINE", label: "En ligne" }, { key: "", label: "Pas encore décidé" }] : [{ key: "IN_STORE", label: "En magasin" }, { key: "TAKEAWAY", label: "Drive / retrait" }, { key: "DELIVERY", label: "Livraison" }]} onChange={(key) => changeContext({ purchaseMode: key as PlannedExpenseContext["purchaseMode"] || undefined })} />
    {context.purchaseMode === "ONLINE" ? <label className="mt-3 grid max-w-md gap-1 text-sm">Sur quel site ? · facultatif<input className={builderInput} value={context.seller ?? ""} onChange={(event) => changeContext({ seller: event.target.value || undefined })} /></label> : context.purchaseMode === "DELIVERY" ? <div className="mt-3">{provider}</div> : <div className="mt-3">{place}</div>}</OptionalAction>;

  const selectContact = (ref: ProspectivePersonRef) => setBuilder((state) => {
    const contact = ref.kind === "CONTACT" ? SOCIAL_CONTACTS_V1.find((part) => part.key === ref.contactKey) : undefined;
    const subtype = contact?.kind === "FAMILY" ? "family_visit" : "friend_visit";
    const newRoot = rootAssetModule("visit_trip", subtype);
    const updated = changeBuilderContext(state, { ...state.draft.context, personVisited: ref });
    return { ...updated, draft: { ...updated.draft, subtypeKey: subtype, costItems: updated.draft.costItems.map((item) => ({ ...item, modulePath: item.modulePath?.[1] ? [newRoot, item.modulePath[1]] : [newRoot] })) } };
  });
  const commit = (item: CostItem) => setBuilder((state) => commitBuilderCost(state, { ...item, modulePath: path,
    baselineKey: path.length === 1 && !bring && !item.assetKey?.endsWith(":delivery_fee") && !item.assetKey?.endsWith(":service_fee") ? state.quickBaseline ?? null : null }));
  const activateChild = (child: AssetModule) => { setBuilder((state) => acceptBuilderChild(state, child)); setPathChild(child); setBring(false); };
  const moduleLabels: Partial<Record<AssetModule, string>> = { restaurant: "Repas au restaurant", activity: "Activité", gift: "Cadeau", house_party: "Before", household: "Entretien de la maison", beauty: "Produits de soin" };

  if (step === 1) return <div id="builder-intent" className="mt-5 grid grid-cols-3 gap-4">{BUILDER_INTENTS.map((choice) => <IntentTile key={choice.key} intent={choice} onClick={() => {
    if (!choice.subtype) { selectRoot(choice.family, choice.family === "outing" ? "bar" : choice.family === "activity" ? "cinema" : "beauty"); setStep(2); }
    else selectRoot(choice.family, choice.subtype);
  }} />)}</div>;
  if (step === 2) return <div id="builder-context" className="mt-6 grid gap-6"><ChoiceTiles label={intent === "party" ? "Quelle soirée ?" : intent === "activity" ? "Quelle activité ?" : "Que prévoyez-vous d’acheter ?"} value={context.outingKind === "EVENT" ? "EVENT" : draft.subtypeKey ?? undefined}
    choices={intent === "party" ? PARTY_CHOICES : intent === "activity" ? [...PLANNED_SUBTYPE_LABELS.activity, { key: "EVENT", label: "Festival / événement" }] : PURCHASE_CHOICES} onChange={(key) => {
      if (key === "EVENT") { selectRoot("outing", "club_festival"); setBuilder((state) => changeBuilderContext(state, { ...state.draft.context, outingKind: "EVENT" })); }
      else { selectRoot(draft.familyKey, key); if (key === "club_festival") setBuilder((state) => changeBuilderContext(state, { ...state.draft.context, outingKind: "CLUB" })); }
    }} /><button type="button" className={`${builderButton} w-fit`} onClick={() => setStep(1)}>Retour aux projets</button></div>;

  return <div className="mt-5 grid gap-6">
    {undoNotice && builder.undo && <div role="status" className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-indigo-50 px-4 py-3 text-sm"><span>{builder.suspended.length ? "Une précision précédente ne s’applique plus à ce choix." : undoNotice}</span><span className="flex gap-4"><button className="font-semibold text-indigo-800 underline" onClick={() => { setBuilder(undoBuilderChange); setUndoNotice(""); }}>Annuler</button>{builder.suspended.length > 0 && <button className="font-semibold text-indigo-800 underline" onClick={() => { setBuilder(discardSuspended); setUndoNotice(""); }}>Garder ce choix</button>}</span></div>}
    {builder.suspended.length > 0 && !undoNotice && <div id="builder-suspended" className="rounded-xl bg-amber-50 p-3 text-sm">Une précision précédente ne s’applique plus à ce choix. <button className="ml-2 underline" onClick={() => setBuilder(undoBuilderChange)}>Annuler</button><button className="ml-3 underline" onClick={() => setBuilder(discardSuspended)}>Garder ce choix</button></div>}
    {step === 3 && <div id="builder-context" className="grid gap-6">
      {intent === "restaurant" && <>{companions}{date}{occasion}{place}{participants}</>}
      {intent === "fast_food" && <><ChoiceTiles label="Comment allez-vous prendre ce repas ?" value={context.purchaseMode} choices={[{ key: "IN_STORE", label: "Sur place" }, { key: "TAKEAWAY", label: "À emporter" }, { key: "DELIVERY", label: "Livraison" }]} onChange={(key) => changeContext({ purchaseMode: key as PlannedExpenseContext["purchaseMode"] })} />{companions}{date}{isDelivery ? provider : place}{participants}</>}
      {isWork && <><ChoiceTiles label="Pour qui est ce repas ?" value={context.participantPersonIds?.[0]} choices={persons.map((person) => ({ key: person.personId, label: person.displayName }))} onChange={(id) => changeContext({ participantPersonIds: [id] })} />
        {personName && <p className="flex gap-2 text-sm text-slate-600"><MapPin size={16} />{places.find((place) => place.relationships.some((relation) => relation.personName === personName && relation.role === "WORK_MEAL_ANCHOR"))?.commune ?? "Lieu de travail non documenté"}</p>}{date}
        {personName && draft.plannedDate && !isAssumedOnsiteWorkday(draft.plannedDate) && <p className="text-xs text-slate-500">Ce jour est en dehors de l’hypothèse actuelle de travail du lundi au vendredi pour {personName}. Vous pouvez prévoir ce repas quand même.</p>}
        <ChoiceTiles label="Comment est prévu le repas ?" value={context.workMealMode} choices={[{ key: "BOUGHT", label: "Acheté sur place / à emporter" }, { key: "DELIVERED", label: "Livré au travail" }, { key: "FROM_HOME", label: "Apporté de chez nous" }]} onChange={(key) => changeContext({ workMealMode: key as PlannedExpenseContext["workMealMode"], purchaseMode: key === "DELIVERED" ? "DELIVERY" : undefined })} />
        {context.workMealMode === "FROM_HOME" ? <p className="rounded-xl bg-emerald-50 p-3 text-sm">Le repas vient des courses déjà prévues. Aucune dépense de repas au travail n’est ajoutée.</p> : isDelivery ? provider : place}
        {personName && !eligibleWallets.length && <p className="text-xs text-slate-500">Aucun titre-resto n’est actuellement attribué à cette personne dans les données du foyer.</p>}</>}
      {intent === "groceries" && <><ChoiceTiles label="Quelles courses prévoyez-vous ?" value={context.groceriesNature} choices={[{ key: "USUAL", label: "Courses habituelles" }, { key: "TOP_UP", label: "Complément / dépannage" }, { key: "OCCASION", label: "Repas / occasion" }]} onChange={(key) => changeContext({ groceriesNature: key as PlannedExpenseContext["groceriesNature"] })} />{date}{context.groceriesNature === "OCCASION" && occasion}{channel}{context.purchaseMode !== "DELIVERY" && !context.purchaseMode && place}</>}
      {intent === "party" && <>{draft.subtypeKey === "house_party" ? <><ChoiceTiles label="Où aura lieu la soirée ?" value={context.housePartyPlaceMode} choices={[{ key: "OWN_HOME", label: "Chez nous" }, { key: "OTHER_HOME", label: "Chez quelqu’un" }]} onChange={(key) => changeContext({ housePartyPlaceMode: key as PlannedExpenseContext["housePartyPlaceMode"] })} />{context.housePartyPlaceMode === "OTHER_HOME" && <ContactPicker label="Chez qui ?" value={context.host} onChange={(host) => changeContext({ host })} />}</> : context.outingKind === "EVENT" ? <label className="grid max-w-lg gap-1 text-sm font-bold">Quel festival / événement ?<input className={builderInput} value={context.eventName ?? ""} onChange={(event) => changeContext({ eventName: event.target.value || undefined })} placeholder="Ex. Family Piknik" /></label> : <button className="w-fit text-sm text-indigo-700 underline" onClick={() => setStep(2)}>Changer le type de soirée</button>}{date}{occasion}{place}{participants}</>}
      {isVisit && <><ContactPicker label="Qui allez-vous voir ?" value={context.personVisited} onChange={selectContact} />{date}
        <OptionalAction label="Préciser qui y va"><ChoiceTiles label="Qui y va ?" choices={[...persons.map((person) => ({ key: person.personId, label: person.displayName })), { key: "BOTH", label: "Nous deux" }]} value={context.participantPersonIds?.length === persons.length ? "BOTH" : context.participantPersonIds?.[0]} onChange={(key) => changeContext({ participantPersonIds: key === "BOTH" ? persons.map((person) => person.personId) : [key] })} /></OptionalAction>{occasion}{place}</>}
      {intent === "activity" && <><button className="w-fit text-sm text-indigo-700 underline" onClick={() => setStep(2)}>Changer d’activité</button>{date}<OptionalAction label="Préciser avec qui">{companions}{participants}</OptionalAction>{place}</>}
      {intent === "purchase" && <>{draft.subtypeKey === "gift" ? <><ContactPicker label="Pour qui est ce cadeau ?" value={context.gift?.recipient ? { kind: "TEXT", label: context.gift.recipient } : undefined} onChange={(ref) => changeContext({ gift: { recipient: contactLabel(ref) ?? "", occasion: context.gift?.occasion ?? "Sans occasion particulière" } })} />{occasion}</> : <><button className="w-fit text-sm text-indigo-700 underline" onClick={() => setStep(2)}>Changer le type d’achat</button><OptionalAction label="Préciser l’objet ou le produit" active={!!context.purchaseDescription}><label className="grid max-w-lg gap-1 text-sm">Qu’avez-vous prévu ?<input className={builderInput} value={context.purchaseDescription ?? ""} onChange={(event) => changeContext({ purchaseDescription: event.target.value || undefined })} placeholder={draft.subtypeKey === "beauty" ? "Ex. Masque visage" : draft.subtypeKey === "tech" ? "Ex. Téléphone, ordinateur, accessoire" : "Ex. Meuble, veste, équipement"} /></label></OptionalAction>{draft.subtypeKey === "clothing" && <OptionalAction label="Préciser pour qui"><ChoiceTiles label="Pour qui ?" value={context.participantPersonIds?.[0]} choices={persons.map((person) => ({ key: person.personId, label: person.displayName }))} onChange={(id) => changeContext({ participantPersonIds: [id] })} /></OptionalAction>}</>}{date}{channel}</>}
      {intent === "trip" && <><ChoiceTiles label="Quel déplacement ?" value={draft.subtypeKey ?? "trip_stay"} choices={[{ key: "trip_stay", label: "Voyage / séjour" }, { key: "other_trip", label: "Déplacement ponctuel" }]} onChange={(key) => selectRoot("visit_trip", key)} />
        <label className="grid max-w-lg gap-1 text-sm font-bold">Où allez-vous ?<input className={builderInput} value={placeLabel} onChange={(event) => changeContext({ place: event.target.value ? { kind: "TEXT", label: event.target.value, provenance: "USER_DECLARED_PROSPECTIVE" } : undefined })} /></label>{date}{draft.subtypeKey === "trip_stay" && <label className="grid max-w-xs gap-1 text-sm">Retour · facultatif<input className={builderInput} type="date" min={draft.plannedDate ?? undefined} value={context.endDate ?? ""} onChange={(event) => changeContext({ endDate: event.target.value || undefined })} /></label>}{participants}</>}
      {placeLabel && <p className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm font-semibold"><MapPin size={16} aria-hidden="true" />{placeLabel}{related && <span className="font-normal text-slate-500">· {context.place?.kind === "TEXT" ? "lieu déclaré" : "lieu connu"}</span>}</p>}
      {resolved && <PlannedRouteEditor builder={builder} setBuilder={setBuilder} places={places} vehicle={vehicle} targetMonth={targetMonth} persons={persons} />}
      <div className="flex items-center gap-3"><button className={builderButton} onClick={() => setStep(1)}><ArrowLeft size={14} className="mr-2 inline" />Projets</button><button className={builderPrimary} onClick={() => setStep(4)}>{isVisit ? "Quelque chose de prévu ?" : "Prévoir le budget"}<ChevronRight size={14} className="ml-2 inline" /></button></div>
    </div>}
    {step === 4 && <div id="builder-cost" className="grid gap-5">
      {context.workMealMode !== "FROM_HOME" && !isVisit && <section className="rounded-2xl bg-slate-50 p-5">
        {builder.costMode === "QUICK_TOTAL" ? <><label className="grid max-w-sm gap-2 text-base font-bold">{intent === "groceries" || isWork ? "Combien prévoyez-vous ?" : "Quel budget prévoyez-vous ?"}<div className="flex items-center gap-3"><input className={`${builderInput} text-xl`} type="number" min="0.01" step="0.01" value={builder.quickTotal} onChange={(event) => setBuilder((state) => setQuickTotal(state, event.target.value))} /><span>€</span></div></label>
          {eligibleWallets.length > 0 && ["restaurant", "fast_food", "work_meal", "groceries"].includes(root) && <OptionalAction label="Utiliser un titre-resto"><div className="mt-2 grid max-w-lg grid-cols-2 gap-3"><label className="grid gap-1 text-sm">Titre-resto<select className={builderInput} value={selectedWallet} onChange={(event) => setWalletSource(event.target.value as typeof walletSource)}>{eligibleWallets.map((part) => <option key={part.source} value={part.source}>{part.source === "SWILE" ? "Swile" : "Edenred"}</option>)}</select></label><label className="grid gap-1 text-sm">Montant titre-resto (€)<input className={builderInput} type="number" value={walletAmount} onChange={(event) => setWalletAmount(event.target.value)} /></label>
            {root === "restaurant" && <label className="col-span-2 grid gap-1 text-sm">Repas et boissons sans alcool dans ce total (€)<input className={builderInput} type="number" value={mealAmount} onChange={(event) => setMealAmount(event.target.value)} placeholder={builder.quickTotal} /><span className="text-xs text-slate-500">L’alcool reste prévu en banque. Laissez vide si tout le total est éligible.</span></label>}
            <button className={`${builderButton} w-fit`} onClick={() => { try { if (!eligibleWallets.some((part) => part.source === selectedWallet)) throw new Error(); setBuilder((state) => fundBuilderTotal(state, selectedWallet, walletAmount, mealAmount || undefined)); setFundingError(""); } catch { setFundingError("Le titre-resto doit rester dans la part éligible du budget."); } }}>Confirmer le titre-resto</button>{fundingError && <p role="alert" className="text-sm text-red-700">{fundingError}</p>}</div></OptionalAction>}
        </> : builder.costMode === "TARGETED_SPLIT" ? <><p className="text-sm font-bold">Budget et paiement prévus</p><div className="mt-3 grid grid-cols-3 gap-3">{draft.costItems.filter(isRootCost).map((item) => <LocalAssetEditor key={`${item.id}:${item.unitAmount}`} item={item} asset={plannedAsset(item.assetKey ?? "")} wallets={eligibleWallets} categoryAmount onConfirm={(changed) => setBuilder((state) => commitBuilderCost(state, { ...changed, modulePath: [root], baselineKey: item.baselineKey }))} />)}</div></> : null}
        {builder.costMode !== "ITEMIZED" && <button className="mt-4 text-sm font-semibold text-indigo-700 underline" onClick={() => { setBuilder(itemizeBuilderCosts); setUndoNotice("Le total est remplacé par les éléments que vous confirmerez."); }}>{detailActionLabel(root)}</button>}
        {builder.costMode === "ITEMIZED" && canCollapseBuilderCosts(builder) && <button className="mt-4 text-sm font-semibold text-indigo-700 underline" onClick={() => { setBuilder(collapseBuilderCosts); setUndoNotice("Les détails ont été regroupés en un total simple. Annuler restaure les mêmes éléments."); }}>Revenir à un total simple</button>}
        {(intent === "activity" || intent === "trip") && <label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={context.noExpense ?? false} onChange={(event) => changeContext({ noExpense: event.target.checked })} />Aucune dépense pour ce projet</label>}
      </section>}
      {isVisit && <div className="flex flex-wrap gap-3"><button className={builderButton} onClick={() => changeContext({ visitFormat: context.visitFormat === "MEAL" ? "SIMPLE" : "MEAL" })}>{context.visitFormat === "MEAL" ? "✓ Repas ensemble" : "+ Repas ensemble"}</button><button className={builderButton} onClick={() => { setBring(!bring); setPathChild(null); }}>+ Apporter quelque chose</button>{resolved?.children.some((edge) => edge.childModule === "activity") && <button className={builderButton} onClick={() => activateChild("activity")}>+ Faire une activité</button>}</div>}
      {(builder.costMode === "ITEMIZED" || !!pathChild || bring) && <section id="builder-addons" className="grid gap-4">
        {(pathChild || bring) && <div className="flex items-center justify-between"><h4 className="text-base font-bold">{bring ? "Qu’apportez-vous ?" : moduleLabels[pathChild!] ?? "Complément"}</h4><button className="text-sm text-indigo-700 underline" onClick={() => { setPathChild(null); setBring(false); }}>Revenir au projet</button></div>}
        {module === "gift" && <label className="grid max-w-md gap-1 text-sm font-semibold">Pour qui est le cadeau ?<input className={builderInput} value={context.gift?.recipient ?? ""} onChange={(event) => changeContext({ gift: { recipient: event.target.value, occasion: context.gift?.occasion ?? "Sans occasion particulière" } })} /></label>}
        {groups.map((group) => <div key={group}><h5 className="mb-2 text-[11px] font-bold tracking-wider text-slate-500">{group}</h5><div className="grid grid-cols-3 items-start gap-3">{catalog.filter((asset) => uxAssetGroup(asset) === group && !/:(delivery_fee|service_fee)$/u.test(asset.assetKey)).map((asset) => {
          const item = draft.costItems.find((item) => item.assetKey === asset.assetKey && JSON.stringify(item.modulePath ?? [root]) === JSON.stringify(path));
          const edge = resolved?.children.find((edge) => edge.childModule === pathChild);
          return <LocalAssetEditor key={`${asset.assetKey}:${item?.id ?? "new"}:${item?.unitAmount ?? ""}`} asset={asset} item={item} suggestion={prices.find((price) => price.assetKey === asset.assetKey)} wallets={edge?.fundingOverride === "BANK_ONLY" ? [] : eligibleWallets} categoryAmount={module === "groceries" || module === "household"} onConfirm={commit} onRemove={item ? () => setBuilder((state) => removeBuilderCost(state, item.id)) : undefined} />;
        })}</div></div>)}
        <OptionalAction label="Autre élément"><LocalAssetEditor wallets={[]} onConfirm={commit} /></OptionalAction>
        {draft.costItems.filter((item) => (item.modulePath?.at(-1) ?? root) === module && !catalog.some((asset) => asset.assetKey === item.assetKey) && !(root === "trip" && ["trip:hotel", "trip:airbnb"].includes(item.assetKey ?? "")) && !item.assetKey?.startsWith("transport:") && !item.assetKey?.endsWith(":delivery_fee") && !item.assetKey?.endsWith(":service_fee")).map((item) => <LocalAssetEditor key={item.id} item={item} asset={plannedAsset(item.assetKey ?? "")} wallets={eligibleWallets} onConfirm={commit} onRemove={() => setBuilder((state) => removeBuilderCost(state, item.id))} />)}
      </section>}
      {root === "trip" && <TripAccommodation items={draft.costItems} onConfirm={(item) => { setBuilder((state) => commitBuilderCost(state, { ...item, modulePath: [root], baselineKey: null })); setUndoNotice("L’hébergement est confirmé dans les détails du séjour. Le total global est conservé dans Annuler."); }} onRemove={(id) => setBuilder((state) => removeBuilderCost(state, id))} />}
      {root === "house_party" && !draft.costItems.length && !builder.quickTotal && <OptionalAction label="Voir la suggestion habituelle"><p className="text-sm">Vodka 1 · 16 € · Crazy Tiger 2 · 3 € — Total 22 €</p><button className={`${builderButton} mt-3`} onClick={() => { setBuilder((state) => {
        let next = itemizeBuilderCosts(state); for (const [key, quantity, amount] of [["house_party:vodka", "1", "16.00"], ["house_party:crazy_tiger", "2", "3.00"]]) next = commitBuilderCost(next, { id: crypto.randomUUID(), assetKey: key, label: plannedAsset(key)!.label, quantity, unitAmount: amount, baselineKey: null, modulePath: [root], priceSource: "SYSTEM_DEFAULT" }); return next;
      }); }}>Utiliser cette suggestion</button></OptionalAction>}
      {(isDelivery || context.purchaseMode === "ONLINE") && <div className="grid grid-cols-2 items-start gap-3">{["delivery_fee", "service_fee"].map((fee) => { const asset = plannedAsset(`${root}:${fee}`); if (!asset) return null; const item = draft.costItems.find((item) => item.assetKey === asset.assetKey); return <OptionalAction key={fee} label={asset.label} active={!!item}><p className="mb-2 text-xs text-slate-500">Si un total est saisi, ces frais en précisent la composition.</p><LocalAssetEditor asset={asset} item={item} wallets={[]} categoryAmount initiallyEditing={!item} onConfirm={(item) => setBuilder((state) => commitBuilderCost(state, { ...item, modulePath: [root], baselineKey: null }))} onRemove={item ? () => setBuilder((state) => removeBuilderCost(state, item.id)) : undefined} /></OptionalAction>; })}</div>}
      <div className="flex flex-wrap gap-2">{suggestedBuilderChildren(builder).map((child) => <button className={builderButton} key={child} onClick={() => activateChild(child)}>+ {moduleLabels[child] ?? child}</button>)}
        <OptionalAction label="Ajouter autre chose"><div className="flex flex-wrap gap-2">{availableBuilderChildren(builder).map((child) => <button className={builderButton} key={child} onClick={() => activateChild(child)}>+ {moduleLabels[child] ?? child}</button>)}</div></OptionalAction>
        {builder.acceptedChildren.map((child) => <button className={builderButton} key={child} onClick={() => { setPathChild(child); setBring(false); }}>Modifier {moduleLabels[child] ?? child}</button>)}</div>
      {resolved && <PlannedRouteEditor builder={builder} setBuilder={setBuilder} places={places} vehicle={vehicle} targetMonth={targetMonth} persons={persons} />}
      {resolved?.baseline.mode === "ASK" && activeDraft.costItems.some(isRootCost) && <fieldset className="rounded-xl bg-slate-50 p-4 text-sm"><legend className="px-1 font-semibold">{root === "groceries" ? "Une partie de ces achats remplace-t-elle vos courses habituelles ?" : root === "fast_food" ? "Sans ce fast-food, auriez-vous probablement acheté un repas similaire ce mois-ci ?" : "Sans ce restaurant, auriez-vous probablement fait une autre sortie similaire ce mois-ci ?"}</legend><div className="mt-2 flex flex-wrap gap-4"><label className="flex gap-2"><input type="radio" name="root-habit" checked={builder.quickBaseline === null} onChange={() => setBuilder((state) => setBuilderRootBaseline(state, null))} />Non, c’est en plus</label><label className="flex gap-2"><input type="radio" name="root-habit" checked={!!builder.quickBaseline} onChange={() => setBuilder((state) => setBuilderRootBaseline(state, resolved.baseline.key))} />Oui, cela remplace une dépense déjà probable</label></div></fieldset>}
      {resolved?.baseline.mode === "AUTO" && <p className="text-xs text-slate-500">Ce projet remplace une partie des {isWork ? "repas déjà estimés pour cette personne" : "courses déjà estimées"}.</p>}
      <div className="sticky bottom-4 z-20 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-indigo-200 bg-white/95 p-4 shadow-lg backdrop-blur"><div><strong className="text-lg">{builderMoney(summary.gross)}</strong><p className="text-xs text-slate-500">{activeDraft.costItems.length} élément(s) · Banque {builderMoney(summary.bank)}{Number(summary.swile) > 0 && ` · Swile ${builderMoney(summary.swile)}`}{Number(summary.edenred) > 0 && ` · Edenred ${builderMoney(summary.edenred)}`}{Number(summary.fuel) > 0 && ` · usage carburant ${builderMoney(summary.fuel)}`}</p></div><div className="flex gap-3"><button className={builderButton} onClick={() => setStep(3)}>Modifier les précisions</button><ContextualBlockerCTA label="Voir l’effet sur notre mois" busy={busy} issues={readiness.issues} onClick={onPreview} onRepair={repair} /></div></div>
    </div>}
  </div>;
}
