export type {
  CapabilityRequirement,
  CorpusAuthority,
  CorpusSlice,
  DependencyRef,
  GlobalAnalysisScopeHash,
  GlobalAnalysisScopeV2,
  GlobalAnalysisTimeV2,
  GlobalCapability,
  GlobalCapabilityState,
  GlobalCoverageDimension,
  GlobalCoverageMeasure,
  GlobalCoverageSet,
  GlobalDependencyConsumption,
  GlobalDependencyDeclaration,
  GlobalDependencyDigest,
  GlobalEngineIdentity,
  GlobalEntityScopePolicy,
  GlobalInvalidationScope,
  GlobalKnowledgeValue,
  GlobalMaterialityCandidate,
  GlobalMethodSignature,
  GlobalNaturalGrain,
  GlobalPartialReason,
  GlobalPersonScopeKind,
  GlobalPersonScopePolicy,
  GlobalResolvedNaturalWindow,
  GlobalSupport,
  GlobalSupportStatus,
  GlobalTimeWindowPolicy,
  GlobalValueProvenance,
  HistoricalLookback,
  NormalizedGlobalAnalysisFilters,
  NormalizedGlobalAnalysisScopeV2,
  PolicyRef,
  PublicationOutputRef,
} from "./types";
export {
  assertGlobalDependencyClosure,
  assertNoLiveTailStructuralDependencies,
  normalizeGlobalAnalysisScopeV2,
  parseCorpusSlice,
  parseGlobalAnalysisScopeV2,
  parseGlobalCapability,
  parseGlobalCoverageMeasure,
  parseGlobalCoverageSet,
  parseGlobalDependencyDeclaration,
  parseGlobalEngineIdentity,
  parseGlobalEntityScopePolicy,
  parseGlobalKnowledgeValue,
  parseGlobalMaterialityCandidate,
  parseGlobalPersonScopePolicy,
  parseGlobalResolvedNaturalWindow,
  parseGlobalSupport,
  parseGlobalTimeWindowPolicy,
  parseGlobalValueProvenance,
  parseHistoricalLookback,
  parsePolicyRef,
  type GlobalPersonScopeValidationContext,
  type GlobalScopeValidationContext,
} from "./validation";
export {
  canonicalSerializeGlobal,
  canonicalSerializeGlobalAnalysisScopeV2,
  computeGlobalAnalysisScopeV2Hash,
  computeGlobalDependencyDeclarationDigest,
  computeGlobalEngineSignature,
} from "./hash";
export {
  assertCapabilityRespectsAuthorityGates,
  globalAuthorityGates,
  parseGlobalAuthorityGateId,
  type GlobalAuthorityGate,
  type GlobalAuthorityGateId,
} from "./authority-gates";
