import type { PlannerJsonObject } from "./json";
import type { PlanSemanticStateV1 } from "./semantic-state";
import type { PlannerDiagnostic, PlannerKnowledge } from "./diagnostics";
import type { PlanProjectionV1 } from "./projection-contract";
import type { PlanScenarioPreview } from "./compiler-contract";
import type { ComponentSelectionV1, ComponentSlotDefinition } from "./component-contract";
import type { SemanticMutation, AdjustmentCapability } from "./adjustment-contract";
export type ComposerAssetView = Readonly<{ assetKey: string; kind: "CONTEXT_ASSET" | "SLOT_OPTION_ASSET" | "PLAN_CONTROL" | "RESERVATION_CONTROL";
  label: string; iconKey: string; capabilityRef: string; provenance: "STRUCTURAL_DEFAULT" | "PERSONAL_SUGGESTION" | "EXPLICIT_USER_DECISION" | "DERIVED_CONSEQUENCE";
  templateKey?: string; optionKey?: string; optionKind?: "COMPONENT" | "MOBILITY_INTENT" }>;
export type ComposerLibraryView = Readonly<{ sections: readonly Readonly<{ sectionKey: string; assetKeys: readonly string[] }>[];
  searchableAssets: readonly ComposerAssetView[] }>;
export type ComposerCardView = Readonly<{ cardId: string; targetRef: string; label: string; kind: "BASELINE_CONTROL" | "DISCRETIONARY_CONTROL" | "SAVINGS";
  value: PlannerJsonObject; knowledge: PlannerKnowledge; capability: AdjustmentCapability | null; historicalReferences: PlannerJsonObject | null }>;
export type ContextSocketView = Readonly<{ contextOccurrenceId: string; slotKey: string;
  cardinality: ComponentSlotDefinition["cardinality"]; visualState: "HABITUAL" | "SUGGESTED" | "CHOSEN" | "DERIVED" | "UNRESOLVED";
  currentItems: readonly ComponentSelectionV1[]; capabilityRefs: readonly string[] }>;
export type ComposerContextCardView = Readonly<{ contextOccurrenceId: string; templateKey: string; label: string;
  parentContextOccurrenceId: string | null; childContextOccurrenceIds: readonly string[]; externalIntentId: string | null;
  readOnly: boolean; fields: PlannerJsonObject; components: readonly PlannerJsonObject[];
  knowledge: PlannerKnowledge; capabilityRefs: readonly string[]; sockets: readonly ContextSocketView[] }>;
export type ComposerCockpitView = PlanProjectionV1;
export type ComposerBoardView = Readonly<{ targetMonth: string; baselineControls: readonly ComposerCardView[];
  discretionaryControls: readonly ComposerCardView[]; contexts: readonly ComposerContextCardView[]; savings: readonly ComposerCardView[];
  cockpit: ComposerCockpitView; diagnostics: readonly PlannerDiagnostic[];
  draft: Readonly<{ dirty: boolean; semanticStateDigest: string; undoCount: number; redoCount: number }> }>;
export type DropTarget = Readonly<{ kind: "BOARD_ZONE" | "CONTEXT_SOCKET" | "TRASH"; contextOccurrenceId?: string; slotKey?: string }>;
export type DropCapability = Readonly<{ sourceAssetKey: string; target: DropTarget; resolution: "ACCEPTED" | "NEEDS_CHOICE" | "BLOCKED";
  semanticAction: "ADD_CONTEXT" | "PATCH_CONTEXT" | "REMOVE_CONTEXT" | null; previewSupported: boolean; constraint: string | null; choices: readonly string[] }>;
export type DropResolution = Readonly<{ capability: DropCapability; semanticMutation: SemanticMutation | null }>;
export type MonthComposerReadModel = Readonly<{ version: string; semanticState: PlanSemanticStateV1;
  library: ComposerLibraryView; board: ComposerBoardView; dropCapabilities: readonly DropCapability[];
  preview: PlanScenarioPreview; activeRevisionId: string | null; activeRevisionNumber: number }>;
