import {
  BadgeCheck,
  Banknote,
  Bike,
  BriefcaseBusiness,
  Building2,
  Cake,
  Camera,
  CarFront,
  Circle,
  FileText,
  Flower2,
  Fuel,
  House,
  Laptop,
  MapPin,
  Music,
  PartyPopper,
  Pill,
  Plane,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Theater,
  TriangleAlert,
  Users,
  UtensilsCrossed,
  Waves,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const semanticIcons: Readonly<Record<string, LucideIcon>> = Object.freeze({
  shopping: ShoppingBag,
  groceries: ShoppingCart,
  administrative: FileText,
  bank_cash: Banknote,
  celebration: PartyPopper,
  home: House,
  culture: Theater,
  nightlife: Music,
  leisure: Bike,
  permit_exam: BadgeCheck,
  driving_lesson: CarFront,
  food_delivery: UtensilsCrossed,
  restaurant: UtensilsCrossed,
  medical: Stethoscope,
  pharmacy: Pill,
  family: Users,
  friends: Users,
  personal_care: Sparkles,
  travel: Plane,
  vehicle_service: Wrench,
  fuel: Fuel,
  business_trip: BriefcaseBusiness,
  work_site: Building2,
  remote_work: Laptop,
  funeral: Flower2,
  birthday: Cake,
  family_event: Users,
  home_project: House,
  photo_project: Camera,
  personal_project: Sparkles,
  incident_repair: TriangleAlert,
  techno_night: Music,
  event_outing: MapPin,
  excursion: MapPin,
  beach: Waves,
  weekend_trip: Plane,
  moment: Circle,
});

export function HistorySemanticIcon({
  iconKey,
  size = 14,
  className,
}: {
  readonly iconKey: string;
  readonly size?: number;
  readonly className?: string;
}) {
  const Icon = semanticIcons[iconKey] ?? Circle;
  return <Icon aria-hidden focusable="false" size={size} className={className} />;
}
